# Generated by Django 5.0.2 on 2024-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено ли сообщение'),
        ),
    ]
